### ISSUE TITLE
Yarn not found, but I downloaded it and its up!

### ISSUE THREAD

**Issue by ElijahChase** [RayzrDev/SharpBot#137] opened 2018-05-16 21:22 UTC
It only doesn't work in the run.bat. And Install.bat just freezes.

**Comment by Rayzr522** [comment] 2018-05-16 21:26
1. Run.bat and Install.bat are no longer used. If you downloaded the bot as a ZIP file, then you installed it wrong. Delete the SharpBot folder and ZIP file and follow the instructions in the [installation section](https://github.com/RayzrDev/SharpBot#installing). 
2. You are clearly on Windows since you're trying to run the Run.bat and Install.bat files, so you are most likely suffering from a common Windows issue; Yarn is often not recognized until after a reboot. This is a common problem, and the cause has yet to be determined. It is not an issue with SharpBot or any of my software, but rather with either Windows or Yarn.

Please reboot, delete the SharpBot folder and ZIP file, and then [reinstall properly](https://github.com/RayzrDev/SharpBot#installing).

**Comment by ElijahChase** [comment] 2018-05-16 21:55
Thanks!

**Comment by Rayzr522** [comment] 2018-05-16 21:58
Assuming you have resolved everything, I am going to close this issue now.

**Closed by Rayzr522** 2018-05-16 21:58 UTC
